redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
command = "npm ci --no-audit --no-fund && npm run -w frontend build"
publish = "frontend/dist"

[build.environment]
NODE_VERSION = "20"
VITE_API_URL = "https://welovemovies-api-francisco.fly.dev/api"
ROLLUP_DISABLE_NATIVE = "1"
ROLLUP_SKIP_NODEJS_NATIVE = "1"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[redirects.query]

[redirects.conditions]

[redirects.headers]