THEATERS_SEED = [
    {
        "name": "Regal City Center",
        "address_line_1": "801 C St.",
        "address_line_2": "",
        "city": "Vancouver",
        "state": "WA",
        "zip": "98660",
    },
    {
        "name": "Hollywood Theatre",
        "address_line_1": "4122 NE Sandy Blvd.",
        "address_line_2": "",
        "city": "Portland",
        "state": "OR",
        "zip": "97212",
    },
    {
        "name": "Regal Tigard",
        "address_line_1": "11626 SW Pacific Hwy",
        "address_line_2": "",
        "city": "Tigard",
        "state": "OR",
        "zip": "97223",
    },
    {
        "name": "Cinemax",
        "address_line_1": "11212 SW Hwy",
        "address_line_2": "",
        "city": "Austin",
        "state": "TX",
        "zip": "75689",
    },
    {
        "name": "Cinemark",
        "address_line_1": "546 Movie St",
        "address_line_2": "",
        "city": "Tigard",
        "state": "San Antonio",
        "zip": "78345",
    },
    {
        "name": "Edward Cinema",
        "address_line_1": "110 Katy Frwy",
        "address_line_2": "",
        "city": "Houston",
        "state": "TX",
        "zip": "77540",
    },
    {
        "name": "Showbiz",
        "address_line_1": "Hwy 146",
        "address_line_2": "",
        "city": "Mont Belview",
        "state": "TX",
        "zip": "77535",
    },
    {
        "name": "Rooftop Cinema",
        "address_line_1": "1700 Post Oak",
        "address_line_2": "",
        "city": "Houston",
        "state": "TX",
        "zip": "77056",
    },
    {
        "name": "AMC",
        "address_line_1": "120 Cypress Wood",
        "address_line_2": "",
        "city": "Austin",
        "state": "TX",
        "zip": "75634",
    },
    {
        "name": "Grandview Cinema",
        "address_line_1": "123 Main St",
        "address_line_2": "",
        "city": "Austin",
        "state": "TX",
        "zip": "73301",
    },
    {
        "name": "Sunset Theater",
        "address_line_1": "456 Oak Ave",
        "address_line_2": "",
        "city": "Denver",
        "state": "CO",
        "zip": "80202",
    },
    {
        "name": "Paramount Movie House",
        "address_line_1": "789 Broadway",
        "address_line_2": "",
        "city": "New York",
        "state": "NY",
        "zip": "10003",
    },
    {
        "name": "Riverwalk Cinemas",
        "address_line_1": "101 River Rd",
        "address_line_2": "",
        "city": "Chicago",
        "state": "IL",
        "zip": "60601",
    },
    {
        "name": "Crescent Bay Theater",
        "address_line_1": "202 Ocean Blvd",
        "address_line_2": "",
        "city": "Los Angeles",
        "state": "CA",
        "zip": "90028",
    },
    {
        "name": "Maple Grove Cinemas",
        "address_line_1": "303 Maple St",
        "address_line_2": "",
        "city": "Minneapolis",
        "state": "MN",
        "zip": "55401",
    },
    {
        "name": "Capitol Hill Theater",
        "address_line_1": "404 Pine St",
        "address_line_2": "",
        "city": "Seattle",
        "state": "WA",
        "zip": "98101",
    },
    {
        "name": "Liberty Square Cinemas",
        "address_line_1": "505 Liberty Ave",
        "address_line_2": "",
        "city": "Philadelphia",
        "state": "PA",
        "zip": "19103",
    },
    {
        "name": "Bluebonnet Theaters",
        "address_line_1": "606 Elm St",
        "address_line_2": "",
        "city": "Houston",
        "state": "TX",
        "zip": "77002",
    },
    {
        "name": "Desert Star Cinema",
        "address_line_1": "707 Desert Dr",
        "address_line_2": "",
        "city": "Phoenix",
        "state": "AZ",
        "zip": "85004",
    },
]