name: Deploy frontend to Netlify

on:
  push:
    branches: [ main ]   # <-- change to your default branch if not 'main'
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
      - "netlify.toml"
  workflow_dispatch: {}   # allow manual runs from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          # If you want Actions to set this rather than netlify.toml
          VITE_API_URL: https://welovemovies-api-francisco.fly.dev/api
          # Work around Rollup native on CI just in case
          ROLLUP_DISABLE_NATIVE: "1"
          ROLLUP_SKIP_NODEJS_NATIVE: "1"
        run: npm run build

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy to Netlify (production)
        run: |
          netlify deploy \
            --dir=dist \
            --prod \
            --site="$NETLIFY_SITE_ID" \
            --auth="$NETLIFY_AUTH_TOKEN"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}