name: Deploy frontend to Netlify

on:
  push:
    branches: [ main ]             # change if your default branch is different
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
      - "netlify.toml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"             # OK without a lockfile; no cache-dependency-path

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build
        env:
          VITE_API_URL: https://welovemovies-api-francisco.fly.dev/api
          ROLLUP_DISABLE_NATIVE: "1"
          ROLLUP_SKIP_NODEJS_NATIVE: "1"
        run: npm run build

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy to Netlify (production)
        run: |
          netlify deploy \
            --dir=dist \
            --prod \
            --site="$NETLIFY_SITE_ID" \
            --auth="$NETLIFY_AUTH_TOKEN"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}